### ISSUE TITLE
SMP process management

### ISSUE THREAD

**Issue by aguinot** [CosmoStat/shapepipe#278]
When lauching a job through the PBS system in SMP, a lot of threads are created that use a lot of CPU power (not a sleeping process). Can be check by logging to the compute node interactively with :
```
qsub -I -l nodes=[NODE_NAME]:ppn=1
```
And then using htop to check the CPU usage.

Can be reproduced by launching an SMP job with PBS.

Bug seen on CANDIDE with PBS.

**Comment by martinkilbinger** [comment]
I think this can be closed.
